# This is a basic workflow to help you get started with Actions

name: Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Latitude_Drivers:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: Execute Main Loop
        env:
          API_KEY: ${{ secrets.VT_API_KEY }}
        run: |
          ./scripts/Dell/Latitude.ps1
  Problem_Script:
    runs-on: windows-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Execute
      run: |
        ./execution.ps1
