# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  User_Agent:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - name: Verify User Agent String
        run: |
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
          $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::InternetExplorer  # Useragent string for InternetExplorer (9.0)
          $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome            # Useragent string for Chrome (7.0)
          $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox           # Useragent string for Firefox (4.0)
          $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Opera             # Useragent string for Opera (9.0)
          $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Safari            # Useragent string for Safari (5.0)
